# Generated by Django 5.1.1 on 2024-11-05 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electronics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="level",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Уровень поставщика"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="electronics.supplier",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="quantity",
            field=models.IntegerField(verbose_name="Количество товара"),
        ),
    ]
